### ISSUE TITLE
"poring" spelt wrong in Introduction to data storytelling 

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/findingstories.learndata.info#2]
In Adapting to the modern world, "But now it’s also going to be about **poring** over data and equipping yourself with the tools to analyse it and picking out what’s interesting."

Should be, "pouring"

**Comment by davetaz** [comment]
changed to studying. Pur and Pore are very different. https://www.grammarly.com/blog/pore-over-pour-over/
